version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge"
    groups:
      androidx:
        patterns:
          - "androidx*"
      ktor:
        patterns:
          - "io.ktor*"
      compose:
        patterns:
          - "org.jetbrains.compose*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "dependencies"
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"git a