/*
 *  Copyright (c) 2026 Piyush Daiya
 *  *
 *  * Permission is hereby granted, free of charge, to any person obtaining a copy
 *  * of this software and associated documentation files (the "Software"), to deal
 *  * in the Software without restriction, including without limitation the rights
 *  * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  * copies of the Software, and to permit persons to whom the Software is
 *  * furnished to do so, subject to the following conditions:
 *  *
 *  * The above copyright notice and this permission notice shall be included in all
 *  * copies or substantial portions of the Software.
 *  *
 *  * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  * SOFTWARE.
 */

package org.vaachak.reader.core.domain.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single OPDS feed entry in the local database.
 *
 * This data class defines the schema for the `opds_feeds` table, storing all the
 * necessary information to connect to and authenticate with an OPDS server.
 *
 * @property id The unique identifier for the feed entry, auto-generated by the database.
 * @property title The user-facing name of the OPDS feed (e.g., "Calibre Library").
 * @property url The base URL of the OPDS feed. This is a critical field for connecting to the server.
 * @property username Optional username for feeds that require Basic HTTP Authentication.
 * @property password Optional password for feeds that require Basic HTTP Authentication.
 * @property isPredefined A flag indicating if this is a pre-configured feed that ships with the app.
 * @property allowInsecure A flag to indicate whether to allow connections to this feed over an insecure
 *                         (non-HTTPS or self-signed certificate) connection. Useful for local servers.
 */
@Entity(tableName = "opds_feeds")
data class OpdsEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val title: String,
    val url: String,
    val username: String? = null,
    val password: String? = null,
    val isPredefined: Boolean = false,
    val allowInsecure: Boolean = false // New Field
)
