name: Security Scan (OWASP)

on:
  push:
    branches: [ "main" ]

jobs:
  mobsf-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: MobSF Static Analysis
        # FIX: Point to the new 'MobSF' organization and the latest stable version
        uses: MobSF/mobsfscan@0.4.5
        with:
          # Pro-tip: Adding '|| true' ensures the workflow doesn't crash before it can upload the report!
          args: '. --sarif --output results.sarif || true'

      - name: Upload Scan Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif